# -*- coding: utf-8 -*-
"""Gradient_Descent_Demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IpVDnx8mAf9AXJ9tYO2ppjCLX5wzjYhA
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Generate data using a dummy function
X=np.arange(10)
Y=(X-5)**2+3
print(X,Y)

# Visualize
print(plt.style.available)
plt.style.use("seaborn-v0_8-darkgrid") # Corrected style name
plt.plot(X,Y)
plt.xlabel('X')
plt.ylabel('Y')
plt.title('Gradient Descent')
plt.show()

# Gradient Descent
# initiate x with any random value
x=0
lr=0.1
plt.plot(X,Y)
for i in range(50):
  grad = 2*(x-5)
  x=x-lr*grad
  y= (x-5)**2+3
  plt.scatter(x,y)
  print(x)